name: scalable_element
version: 0.0.1
author: Matthew Cross
description: A pub package
homepage: https://github.com/mcross1882/scalable_element
environment:
  sdk: 1.5.3
dependencies:
  polymer: '>=0.11.0 <0.12.0'
transformers:
- polymer:
    entry_points: web/index.html
